# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.14.0
    hooks:
      - id: reuse

  - repo: local
    hooks:
      - id: check-if-version-is-bumped
        name: check-if-version-is-bumped
        entry: bash -c '
          if [[ -z $(git diff develop --staged -G"pkgver|pkgrel" package/PKGBUILD) ]] &&
             [[ -z $(git diff develop..HEAD -G"pkgver|pkgrel" package/PKGBUILD) ]];
          then
            exit 1;
          fi'
        language: system
