# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carbonio-files-ce
  title: Carbonio Files CE service
  description: |
    Service that allows to upload/download and share files.
    It exposes a connector to use the carbonio-preview-ce in order to preview files and
    a connector to open the editing collaboration tool (carbonio-docs-editor).
  tags:
    - java
    - backend
  links:
    - url: https://github.com/Zextras/carbonio-files-ce/blob/develop/README.md
      title: README
spec:
  type: service
  lifecycle: production
  owner: shuffled-waffles
  providesApis:
    - carbonio-files-ce-rest-api
    - carbonio-files-ce-graphql-api
  dependsOn:
    - component:carbonio-files-db
    - component:carbonio-user-management
    - component:carbonio-storages-ce
    - component:carbonio-preview-ce
    - component:carbonio-mailbox

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: carbonio-files-ce-rest-api
  title: Carbonio Files CE REST APIs
  description: Carbonio Files Community Edition REST APIs.
  tags:
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: shuffled-waffles
  definition:
    $text: https://github.com/Zextras/carbonio-files-ce/blob/develop/core/src/main/resources/api/rest.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: carbonio-files-ce-graphql-api
  title: Carbonio Files CE GraphQL APIs
  description: Carbonio Files Community Edition GraphQL APIs.
  tags:
    - graphql
spec:
  type: graphql
  lifecycle: production
  owner: shuffled-waffles
  definition:
    $text: https://github.com/Zextras/carbonio-files-ce/blob/develop/core/src/main/resources/api/schema.graphql