version = 1
SPDX-PackageName = "carbonio-files-ce"
SPDX-PackageSupplier = "Zextras <packages@zextras.com>"
SPDX-PackageDownloadLocation = "https://github.com/Zextras/carbonio-files-ce"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "CHANGELOG.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Zextras"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "THIRDPARTIES"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Zextras"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Zextras"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = ".releaserc.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Zextras"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "package/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "docker/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Zextras"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "yap.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras s.r.l"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = ["mvnw", "mvnw.cmd"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2001-2024 The Apache Software Foundation <https://www.apache.org>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "**/src/main/resources/META-INF/native-image/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"
