<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <licenses>
    <license>
      <comments>Copyright (C) 2022 Zextras, https://www.zextras.com</comments>
      <name>AGPL-3.0-only</name>
    </license>
  </licenses>

  <artifactId>carbonio-files-ce-boot</artifactId>
  <name>carbonio-files-ce-boot</name>

  <parent>
    <artifactId>carbonio-files-ce</artifactId>
    <groupId>com.zextras.carbonio.files</groupId>
    <version>${revision}${changelist}</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>com.zextras.carbonio</groupId>
      <artifactId>carbonio-systemd-notify</artifactId>
      <version>1.0.1</version>
    </dependency>

    <dependency>
      <groupId>com.zextras.carbonio.files</groupId>
      <artifactId>carbonio-files-ce-core</artifactId>
      <version>${project.parent.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler.version}</version>
        <configuration>
          <release>${java-compiler.version}</release>
          <source>${java-compiler.version}</source>
          <target>${java-compiler.version}</target>
          <compilerArgs>
            <arg>--enable-preview</arg>
          </compilerArgs>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>module-info.class</exclude>
                    <exclude>META-INF/*.MF</exclude>
                    <exclude>META-INF/*.md</exclude>
                    <exclude>META-INF/DEPENDENCIES</exclude>
                    <exclude>META-INF/LICENSE</exclude>
                    <exclude>META-INF/LICENSE.txt</exclude>
                    <exclude>META-INF/NOTICE</exclude>
                  </excludes>
                </filter>
              </filters>
              <finalName>carbonio-files-ce-${project.parent.version}-jar-with-dependencies</finalName>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>com.zextras.carbonio.files.Boot</mainClass>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>