// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

package com.zextras.carbonio.files.sdk.streaming;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpClient.Version;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Map;
import java.util.function.Supplier;

/**
 * Static helpers, built on {@link java.net.http.HttpClient}, for streaming blob upload/download
 * against the {@code /internal} REST endpoints generated by {@code rest/sdk-parent}. Ported,
 * RAW-ONLY, from {@code carbonio-quarkus-extensions}' {@code rest/sdk-support} module (removed
 * there once the extensions repo stopped shipping a shared streaming helper) since this SDK still
 * needs it: files' internal blob endpoints ({@code InternalBlobResource}) carry item metadata
 * (filename, parent id, node id, overwrite-version) in HTTP headers over a raw octet-stream body,
 * never a {@code multipart/form-data} envelope, so only the raw-body helpers are ported --
 * {@code uploadStream} (multipart) and its {@code MultipartStreamPublisher} are intentionally
 * dropped.
 *
 * <p>Neither {@link #uploadStreamRaw} nor {@link #downloadStream} ever buffers the whole file in
 * memory: upload streams a fresh {@link InputStream} (obtained per attempt from a caller-supplied
 * {@link Supplier}) straight into the request body via {@link
 * HttpRequest.BodyPublishers#ofInputStream(Supplier)}, and download hands back the live response
 * {@link InputStream} unread.
 */
public final class RestStreamingSupport {

  private static final Duration CONNECT_TIMEOUT = Duration.ofSeconds(30);

  /** Upper bound on how much of a non-2xx response body is read into an exception message. */
  private static final int MAX_ERROR_BODY_BYTES = 2048;

  private RestStreamingSupport() {}

  /**
   * Builds an HTTP/1.1 {@link HttpClient} suitable for streaming requests. HTTP/1.1 is pinned
   * explicitly because the target services in this mesh only speak HTTP/1.1.
   */
  public static HttpClient http1Client() {
    return HttpClient.newBuilder().version(Version.HTTP_1_1).connectTimeout(CONNECT_TIMEOUT).build();
  }

  /**
   * Issues a GET request and returns the response body as a live, streamed {@link InputStream}
   * (never buffered in memory). The caller is responsible for closing the returned stream.
   *
   * @param requestTimeout overall request timeout applied via {@link
   *     HttpRequest.Builder#timeout(Duration)}, or {@code null} for no timeout (recommended for
   *     very large transfers where an arbitrarily long duration is expected).
   * @throws IOException if the request fails, or the response status is not 2xx (in which case the
   *     error body, truncated to {@value #MAX_ERROR_BODY_BYTES} bytes, is drained and included in
   *     the exception message).
   */
  public static InputStream downloadStream(
      HttpClient client, URI uri, Map<String, String> headers, Duration requestTimeout)
      throws IOException, InterruptedException {
    HttpRequest.Builder requestBuilder = HttpRequest.newBuilder(uri).GET();
    headers.forEach(requestBuilder::header);
    if (requestTimeout != null) {
      requestBuilder.timeout(requestTimeout);
    }

    HttpResponse<InputStream> response =
        client.send(requestBuilder.build(), BodyHandlers.ofInputStream());
    int status = response.statusCode();
    if (!isSuccess(status)) {
      throw new IOException(
          "GET "
              + uri
              + " failed with status "
              + status
              + ": "
              + drainErrorBodyTruncated(response.body()));
    }
    return response.body();
  }

  /**
   * Uploads the raw bytes produced by {@code bodyStreamSupplier} as a POST request whose body is
   * the content itself &mdash; no {@code multipart/form-data} envelope &mdash; streamed directly
   * via {@link HttpRequest.BodyPublishers#ofInputStream(Supplier)} (never buffered in memory).
   * This is the helper for endpoints (such as files' internal upload) that carry item metadata
   * (filename, parent id, node id, overwrite-version, ...) in HTTP headers instead of in a
   * multipart body.
   *
   * <p>{@code bodyStreamSupplier} is invoked exactly once per send attempt, so it must return a
   * fresh, unread {@link InputStream} each time it is called (this makes the upload
   * re-subscription-safe: e.g. safe to retry).
   *
   * <p>The {@code Content-Type} header is set from {@code contentType} first, then every entry of
   * {@code headers} is applied on top. Per {@link HttpRequest.Builder#header(String, String)}
   * semantics, this adds rather than replaces, so a caller-supplied {@code Content-Type} entry (if
   * any) is added alongside instead of silently clobbering the one set here.
   *
   * @param requestTimeout overall request timeout applied via {@link
   *     HttpRequest.Builder#timeout(Duration)}, or {@code null} for no timeout (recommended for
   *     very large transfers where an arbitrarily long duration is expected).
   * @throws IOException if the request fails, or the response status is not 2xx (in which case the
   *     response body, truncated to {@value #MAX_ERROR_BODY_BYTES} bytes, is read and included in
   *     the exception message).
   */
  public static HttpResponse<String> uploadStreamRaw(
      HttpClient client,
      URI uri,
      Map<String, String> headers,
      String contentType,
      Supplier<InputStream> bodyStreamSupplier,
      Duration requestTimeout)
      throws IOException, InterruptedException {
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Content-Type", contentType)
            .POST(HttpRequest.BodyPublishers.ofInputStream(bodyStreamSupplier));
    headers.forEach(requestBuilder::header);
    if (requestTimeout != null) {
      requestBuilder.timeout(requestTimeout);
    }

    HttpResponse<String> response = client.send(requestBuilder.build(), BodyHandlers.ofString());
    int status = response.statusCode();
    if (!isSuccess(status)) {
      throw new IOException(
          "POST "
              + uri
              + " failed with status "
              + status
              + ": "
              + truncate(response.body()));
    }
    return response;
  }

  private static boolean isSuccess(int status) {
    return status >= 200 && status < 300;
  }

  private static String drainErrorBodyTruncated(InputStream errorBody) {
    try (errorBody) {
      byte[] bytes = errorBody.readNBytes(MAX_ERROR_BODY_BYTES);
      String text = new String(bytes, StandardCharsets.UTF_8);
      return bytes.length == MAX_ERROR_BODY_BYTES ? text + "...(truncated)" : text;
    } catch (IOException e) {
      return "<unreadable error body: " + e.getMessage() + ">";
    }
  }

  private static String truncate(String body) {
    if (body == null) {
      return "";
    }
    return body.length() > MAX_ERROR_BODY_BYTES
        ? body.substring(0, MAX_ERROR_BODY_BYTES) + "...(truncated)"
        : body;
  }
}
