# SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

scalar BigInteger

enum SharePermission {
    READ_ONLY
    READ_AND_WRITE
    READ_AND_SHARE
    READ_WRITE_AND_SHARE
}

enum NodeSort {
    LAST_EDITOR_ASC
    LAST_EDITOR_DESC
    NAME_ASC
    NAME_DESC
    OWNER_ASC
    OWNER_DESC
    TYPE_ASC
    TYPE_DESC
    UPDATED_AT_ASC
    UPDATED_AT_DESC
    SIZE_ASC
    SIZE_DESC
}

enum ShareSort {
    CREATION_ASC
    CREATION_DESC
    TARGET_USER_ASC
    TARGET_USER_DESC
    SHARE_PERMISSIONS_ASC
    SHARE_PERMISSIONS_DESC
    EXPIRATION_ASC
    EXPIRATION_DESC
}

enum NodeType {
    IMAGE
    VIDEO
    AUDIO
    TEXT
    SPREADSHEET
    PRESENTATION
    FOLDER
    APPLICATION
    MESSAGE
    ROOT
    OTHER
}

enum NotificationType {
    NEW_SHARE
    ADDED_NODE
    REMOVED_NODE
}

enum AddedNodeType {
    UPLOAD
    CREATE
    COPY
    MOVE
}

enum RemovedNodeType {
    DELETE
    MOVE
}

union SharedTarget = User | DistributionList
union Account = User | DistributionList
union Notification = NewShare | AddedNode | RemovedNode

type User {
    id: ID!
    email: String!
    full_name: String!
}

type Config {
    name: String!
    value: String
}

type DistributionList {
    id: ID!
    name: String!
    users(
        limit: Int!,
        cursor: String,
    ): [User]!
}

type Permissions {
    can_read: Boolean!
    can_write_file: Boolean!
    can_write_folder: Boolean!
    can_delete: Boolean!
    can_add_version: Boolean!
    can_read_link: Boolean!
    can_change_link: Boolean!
    can_share: Boolean!
    can_read_share: Boolean!
    can_change_share: Boolean!
}

type Share {
    created_at: BigInteger!
    node: Node!
    share_target: SharedTarget
    permission: SharePermission!
    expires_at: BigInteger
}

type Link {
    id: ID!
    url: String
    node: Node!
    created_at: BigInteger!
    expires_at: BigInteger
    description: String
    access_code: String
}

type CollaborationLink {
    id: ID!
    url: String!
    node: Node!
    created_at: BigInteger!
    permission: SharePermission!
}

type Root {
    id: ID!
    name: String!
}

type SnapshotNode {
    snapshot_node_id: ID!
    node_id: ID!
    owner_id: ID
    name: String!
    type: NodeType!
    created_at: BigInteger!
}

type SnapshotUser {
    snapshot_user_id: ID!
    user_id: ID!
    full_name: String!
    email: String!
}

type NewShare {
    id: ID!
    created_at: BigInteger!
    notification_type: NotificationType!
    node: SnapshotNode!
    triggering_user: SnapshotUser!
}

type AddedNode {
    id: ID!
    created_at: BigInteger!
    notification_type: NotificationType!
    added_node: SnapshotNode!
    destination_folder: SnapshotNode!
    triggering_user: SnapshotUser!
    added_node_type: AddedNodeType!
}

type RemovedNode {
    id: ID!
    created_at: BigInteger!
    notification_type: NotificationType!
    removed_node: SnapshotNode!
    origin_folder: SnapshotNode!
    triggering_user: SnapshotUser!
    removed_node_type: RemovedNodeType!
}

type NodePage {
    nodes: [Node]!
    page_token: String
}

type NotificationPage {
    notifications: [Notification]!
    unread: Int!
    last_seen: BigInteger!
    page_token: String
}

interface Node {
    id: ID!
    creator: User!
    owner: User
    last_editor: User
    created_at: BigInteger!
    updated_at: BigInteger!
    permissions: Permissions!
    name: String!
    description: String!
    type: NodeType!
    flagged: Boolean!
    parent: Node
    rootId: ID
    share(share_target_id: ID!) : Share
    shares(
        limit: Int!,
        cursor: String,
        sorts: [ShareSort!]
    ): [Share]!
    links: [Link]!
    collaboration_links: [CollaborationLink]!
}

type Folder implements Node {
    id: ID!
    creator: User!
    owner: User
    last_editor: User
    created_at: BigInteger!
    updated_at: BigInteger!
    permissions: Permissions!
    name: String!
    description: String!
    type: NodeType!
    parent: Node
    rootId: ID
    flagged: Boolean!
    children(
        limit: Int!,
        sort: NodeSort!
        page_token: String
    ): NodePage!
    share(share_target_id: ID!) : Share
    shares(
        limit: Int!,
        cursor: String,
        sorts: [ShareSort!]
    ): [Share]!
    links: [Link]!
    collaboration_links: [CollaborationLink]!
}

type File implements Node {
    id: ID!
    creator: User!
    owner: User
    last_editor: User
    created_at: BigInteger!
    updated_at: BigInteger!
    permissions: Permissions!
    name: String!
    extension: String
    description: String!
    type: NodeType!
    mime_type: String!
    size: Float!
    digest: String!
    version: Int!
    keep_forever: Boolean!
    cloned_from_version: Int
    parent: Node
    rootId: ID
    flagged: Boolean!
    share(share_target_id: ID!) : Share
    shares(
        limit: Int!,
        cursor: String,
        sorts: [ShareSort!]
    ): [Share]!
    links: [Link]!
    collaboration_links: [CollaborationLink]!
}

interface PublicNode {
    id: ID!
    created_at: BigInteger!
    updated_at: BigInteger!
    name: String!
    type: NodeType!
}

type PublicFolder implements PublicNode {
    id: ID!
    created_at: BigInteger!
    updated_at: BigInteger!
    name: String!
    type: NodeType!
}

type PublicFile implements PublicNode {
    id: ID!
    created_at: BigInteger!
    updated_at: BigInteger!
    name: String!
    extension: String
    type: NodeType!
    mime_type: String!
    size: Float!
}

type PublicNodePage {
    nodes: [PublicNode]!
    page_token: String
}

type Query {
    getNode(
        node_id: ID!
        version: Int
    ) : Node

    findNodes(
        keywords: [String!]
        flagged: Boolean
        shared_by_me: Boolean
        shared_with_me: Boolean
        direct_share: Boolean
        folder_id: String
        cascade: Boolean
        type: NodeType
        owner_id: String
        limit: Int
        page_token: String
        sort: NodeSort
    ) : NodePage

    getVersions(
        node_id: ID!
        versions: [Int!]
    ): [File]!

    getPath(
        node_id: ID!
    ): [Node]!

    getUserById(
        user_id: ID!
    ) : User

    getAccountByEmail(
        email: String!
    ) : Account

    getAccountsByEmail(
        emails: [String!]!
    ) : [Account]!

    getShare(
        node_id: ID!
        share_target_id: ID!
    ): Share

    getLinks(
        node_id: ID!
    ): [Link]!

    getCollaborationLinks(
        node_id: ID!
    ): [CollaborationLink]!

    getRootsList: [Root]!

    getConfigs: [Config]!

    getNotifications(
        update_last_seen: Boolean!
        limit: Int
        page_token: String
    ): NotificationPage

    getPublicNode(
        node_link_id: String!
        access_code: String
    ) : PublicNode

    findPublicNodes(
        folder_id: ID!
        limit: Int
        node_link_id: String
        access_code: String
        page_token: String
    ) : PublicNodePage
}

type Mutation {
    createFolder(
        destination_id: String!
        name: String!
    ) : Node!

    updateNode(
        node_id: String!
        name: String
        description: String
        flagged: Boolean
    ): Node!

    flagNodes(node_ids: [String!], flag: Boolean!) : [ID!]

    trashNodes(node_ids: [String!]) : [ID!]

    restoreNodes(node_ids: [String!]) : [Node]

    moveNodes(node_ids: [String!], destination_id: ID!) : [Node!]

    deleteNodes(node_ids: [String!]): [ID!]

    copyNodes(node_ids: [String!], destination_id: ID!): [Node!]

    deleteVersions(node_id: ID!, versions: [Int!]): [Int]!

    keepVersions(node_id: ID!, versions: [Int!]!, keep_forever: Boolean!) : [Int]!

    cloneVersion(node_id: ID!, version: Int!): File!

    createShare(
        node_id: ID!
        share_target_id: ID!
        permission: SharePermission!
        expires_at: BigInteger
        custom_message: String
    ) : Share!

    updateShares(
        node_id: ID!
        share_target_ids: [String!]!
        permission: SharePermission
        expires_at: BigInteger
    ) : [Share]!

    deleteShares(
        node_id: ID!
        share_target_ids: [String!]!
    ) : [ID]!

    createLink(
        node_id: ID!
        expires_at: BigInteger
        description: String
        access_code: String
    ): Link!

    updateLink(
        link_id: ID!
        expires_at: BigInteger
        description: String
        access_code: String
    ): Link

    deleteLinks(
        link_ids: [String!]!
    ): [ID]!

    createCollaborationLink(
        node_id: ID!
        permission: SharePermission!
    ): CollaborationLink!

    deleteCollaborationLinks(
        collaboration_link_ids: [String!]!
    ): [ID]!
}

schema {
    query: Query
    mutation: Mutation
}
