services:
  consul-mock:
    image: mockserver/mockserver:5.15.0
    container_name: consul-mock
    ports:
      - "127.0.0.1:8500:8000"
    volumes:
      - ./mockserver/consul.json:/config/consul.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/consul.json
    command: -serverPort 8000 -logLevel WARN

  soap-mock:
    image: mockserver/mockserver:5.15.0
    container_name: soap-mock
    ports:
      - "127.0.0.1:8888:8000"
    volumes:
      - ./mockserver/soap.json:/config/soap.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/soap.json
    command: -serverPort 8000 -logLevel WARN

  user-management-mock:
    image: mockserver/mockserver:5.15.0
    container_name: user-management-mock
    ports:
      - "127.78.0.2:20001:8000"
    volumes:
      - ./mockserver/user-management.json:/config/user-management.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/user-management.json
    command: -serverPort 8000 -logLevel WARN

  storages-mock:
    image: mockserver/mockserver:5.15.0
    container_name: storages-mock
    ports:
      - "127.78.0.2:20002:8000"
    volumes:
      - ./mockserver/storages.json:/config/storages.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/storages.json
    command: -serverPort 8000 -logLevel WARN

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: carbonio-files-db
    restart: on-failure

  carbonio-files:
    build:
      context: ./carbonio-files
      dockerfile: Dockerfile
    container_name: carbonio-files
    network_mode: "host"
    volumes:
      - ../../boot/target:/app
    depends_on:
      - postgres
      - consul-mock
    restart: on-failure

  carbonio-files-ui:
    build:
      context: ./carbonio-files-ui
      dockerfile: Dockerfile
    container_name: carbonio-files-ui
    network_mode: "host"
    depends_on:
      - postgres
      - consul-mock
      - carbonio-files
    restart: on-failure
